/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_wangsl_ndktest_NdkJniUtils */

#ifndef _Included_com_example_wangsl_ndktest_NdkJniUtils
#define _Included_com_example_wangsl_ndktest_NdkJniUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_wangsl_ndktest_NdkJniUtils
 * Method:    getClanguageString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_wangsl_ndktest_NdkJniUtils_getClanguageString
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
